MAIN_START      = 0x0000
MAIN_END        = 0x3BFE
MAIN_OTA_START  = 0x3C00
MAIN_OTA_END    = 0x77FE
BOOT_OTA_START  = 0x7800
BOOT_OTA_END    = 0x7B7E
WRITE_OTA_START = 0x7B80
WRITE_OTA_END   = 0x7BFE
BOOT_START      = 0x7C00
BOOT_END        = 0x7F7E
WRITE_START     = 0x7F80
WRITE_END       = 0x7FFE
FLASH_END       = 0x8000


#MAIN_START      = 0x0000
#MAIN_END        = $(shell printf "0x%04x\n" $$(($(MAIN_OTA_START) - 2)))
#MAIN_OTA_START  = 0x3800
#MAIN_OTA_END    = $(shell printf "0x%04x\n" $$(($(WRITE_OTA_START) - 2)))
#WRITE_OTA_START = 0x7000
#WRITE_OTA_END   = $(shell printf "0x%04x\n" $$(($(BOOT_OTA_START) - 2)))
#BOOT_OTA_START  = 0x7400
#BOOT_OTA_END    = $(shell printf "0x%04x\n" $$(($(BOOT_START) - 2)))
#BOOT_START      = 0x7800
#BOOT_END        = $(shell printf "0x%04x\n" $$(($(WRITE_START) - 2)))
#WRITE_START     = 0x7C00
#WRITE_END       = $(shell printf "0x%04x\n" $$(($(FLASH_END) - 2)))
#FLASH_END       = 0x8000

EXTERNAL_MEMORY = false

LFUSE    = 0xFF
HFUSE    = 0xD4
EFUSE    = 0xFA
LOCKFUSE = 0xFF
