MAIN_START      = 0x0000
MAIN_END        = 0x37FE
MAIN_OTA_START  = 0x3800
MAIN_OTA_END    = 0x6FFE
WRITE_OTA_START = 0x7000
WRITE_OTA_END   = 0x73FE
BOOT_OTA_START  = 0x7400
BOOT_OTA_END    = 0x77FE
BOOT_START      = 0x7800
BOOT_END        = 0x7BFE
WRITE_START     = 0x7C00
WRITE_END       = 0x7FFE
FLASH_END       = 0x8000


#MAIN_START      = 0x0000
#MAIN_END        = $(shell printf "0x%04x\n" $$(($(MAIN_OTA_START) - 2)))
#MAIN_OTA_START  = 0x3800
#MAIN_OTA_END    = $(shell printf "0x%04x\n" $$(($(WRITE_OTA_START) - 2)))
#WRITE_OTA_START = 0x7000
#WRITE_OTA_END   = $(shell printf "0x%04x\n" $$(($(BOOT_OTA_START) - 2)))
#BOOT_OTA_START  = 0x7400
#BOOT_OTA_END    = $(shell printf "0x%04x\n" $$(($(BOOT_START) - 2)))
#BOOT_START      = 0x7800
#BOOT_END        = $(shell printf "0x%04x\n" $$(($(WRITE_START) - 2)))
#WRITE_START     = 0x7C00
#WRITE_END       = $(shell printf "0x%04x\n" $$(($(FLASH_END) - 2)))
#FLASH_END       = 0x8000

EXTERNAL_MEMORY = false
